# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstSection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry', :git => 'https://github.com/SnapKit/Masonry.git', :inhibit_warnings => true
  # Pods for FirstSection

  target 'FirstSectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstSectionUITests' do
    # Pods for testing
  end

end
